---
- name: Ensure seaweedfs namespace exists
  kubernetes.core.k8s:
    kubeconfig: "{{ k3s_kubeconfig_path }}"
    api_version: v1
    kind: Namespace
    name: "{{ seaweedfs_namespace }}"
    state: present

- name: Add seaweedfs Helm repository
  kubernetes.core.helm_repository:
    name: seaweedfs
    url: "{{ seaweedfs_chart_repo }}"
  register: repo_added

- name: Update Helm repositories (if repo was added or changed)
  ansible.builtin.command: "{{ helm_binary }} repo update"
  when: repo_added.changed

- name: Install/Upgrade SeaweedFS Helm chart
  kubernetes.core.helm:
    kubeconfig: "{{ k3s_kubeconfig_path }}"
    name: "{{ seaweedfs_release_name }}"
    chart_ref: "seaweedfs/{{ seaweedfs_chart_name }}"
    chart_version: "{{ seaweedfs_chart_version | default(omit) }}"
    release_namespace: "{{ seaweedfs_namespace }}"
    values: "{{ seaweedfs_values }}"
    state: present
  register: helm_result

- name: Patch SeaweedFS service with external IP
  kubernetes.core.k8s:
    kubeconfig: "{{ k3s_kubeconfig_path }}"
    api_version: v1
    kind: Service
    namespace: "{{ seaweedfs_namespace }}"
    name: "{{ seaweedfs_service_name }}"
    merge_type: strategic-merge
    definition:
      spec:
        externalIPs:
          - "{{ seaweedfs_external_ip }}"
  when: seaweedfs_external_ip | length > 0

- name: Wait for service to be available
  ansible.builtin.wait_for:
    host: "{{ seaweedfs_external_ip }}"
    port: 8333
    timeout: 120
  when: seaweedfs_external_ip | length > 0

- name: Display Helm release status
  ansible.builtin.debug:
    msg: "SeaweedFS Helm release '{{ seaweedfs_release_name }}' deployed successfully in namespace '{{ seaweedfs_namespace }}'"
  when: helm_result.changed
